Make remote repo module and add to issue properties
UCL-ARC/qw pull request #11
Opened 2023-10-25 12:49 UTC by stefpiatek

- Not quite convinced that I've got the best place for processing raw issue data into design stages so any thoughts there would be good
- Moved the remote repository files into their own modules and made use of abstract base classes so we have to implement properties
- in tests, can read from filesystem, imagine during testing we may need to pass in a temporary test directory, which we can setup there. Using the frontmatter in markdown to keep all the values that we'd get some the github object
- Next steps might be persisting the current changes to a file?

2023-10-25 14:08 UTC, tim-band requested changes
Just one simple change

2023-10-25 14:08 UTC, tim-band commented on tests/helpers/mock_service.py
> +    """The GitHub service."""
You mean """The FileSystem Service"""

2023-10-25 14:52 UTC, stefpiatek commented on tests/helpers/mock_service.py
> +    """The GitHub service."""
```suggestion
    """The FileSystem Service."""
```

2023-10-26 11:08 UTC, tim-band approved these changes

2023-10-26 11:08 UTC, merged